
INSERT INTO public.author ("name") VALUES('Михаил Булгаков');
INSERT INTO public.author ("name") VALUES('Илья Ильф');
INSERT INTO public.author ("name") VALUES('Евгений Петров');
INSERT INTO public.author ("name") VALUES('Николай Гоголь');
INSERT INTO public.author ("name") VALUES('Александр Дюма');
INSERT INTO public.author ("name") VALUES('Эрих Мария Ремарк');
INSERT INTO public.author ("name") VALUES('Александр Пушкин');
INSERT INTO public.author ("name") VALUES('Виктор Гюго');
INSERT INTO public.author ("name") VALUES('Федор Достоевский');
INSERT INTO public.author ("name") VALUES('Лев Толстой');
INSERT INTO public.author ("name") VALUES('Иван Тургенев');
INSERT INTO public.author ("name") VALUES('Антон Чехов');
INSERT INTO public.author ("name") VALUES('Артур Конан Дойль');
INSERT INTO public.author ("name") VALUES('Александр Грибоедов');
INSERT INTO public.author ("name") VALUES('Эрнест Хемингуэй');
INSERT INTO public.author ("name") VALUES('Жюль Верн');


INSERT INTO public.book (title,date_added) VALUES('Мастер и Маргарита', now());
INSERT INTO public.book (title,date_added) VALUES('Собачье сердце', now());
INSERT INTO public.book (title,date_added) VALUES('Двенадцать стульев', now());
INSERT INTO public.book (title,date_added) VALUES('Мёртвые души', now());
INSERT INTO public.book (title,date_added) VALUES('Граф Монте-Кристо', now());
INSERT INTO public.book (title,date_added) VALUES('Золотой теленок', now());
INSERT INTO public.book (title,date_added) VALUES('Три товарища', now());
INSERT INTO public.book (title,date_added) VALUES('Отверженные', now());
INSERT INTO public.book (title,date_added) VALUES('Евгений Онегин', now());
INSERT INTO public.book (title,date_added) VALUES('Преступление и наказание', now());
INSERT INTO public.book (title,date_added) VALUES('Война и мир', now());
INSERT INTO public.book (title,date_added) VALUES('Повести Белкина', now());
INSERT INTO public.book (title,date_added) VALUES('Ревизор', now());
INSERT INTO public.book (title,date_added) VALUES('Село Степанчиково и его обитатели', now());
INSERT INTO public.book (title,date_added) VALUES('Три мушкетера', now());
INSERT INTO public.book (title,date_added) VALUES('Отцы и дети', now());
INSERT INTO public.book (title,date_added) VALUES('Палата № 6', now());
INSERT INTO public.book (title,date_added) VALUES('Собака Баскервилей', now());
INSERT INTO public.book (title,date_added) VALUES('Братья Карамазовы', now());
INSERT INTO public.book (title,date_added) VALUES('Идиот', now());
INSERT INTO public.book (title,date_added) VALUES('Рудин', now());
INSERT INTO public.book (title,date_added) VALUES('Приключения Шерлока Холмса', now());
INSERT INTO public.book (title,date_added) VALUES('Горе от ума', now());
INSERT INTO public.book (title,date_added) VALUES('Дубровский', now());
INSERT INTO public.book (title,date_added) VALUES('Драма на охоте', now());
INSERT INTO public.book (title,date_added) VALUES('Капитанская дочка', now());
INSERT INTO public.book (title,date_added) VALUES('Униженные и оскорблённые', now());
INSERT INTO public.book (title,date_added) VALUES('Воскресение', now());
INSERT INTO public.book (title,date_added) VALUES('Дворянское гнездо', now());
INSERT INTO public.book (title,date_added) VALUES('Рассказы', now());
INSERT INTO public.book (title,date_added) VALUES('Триумфальная арка', now());
INSERT INTO public.book (title,date_added) VALUES('Подросток', now());
INSERT INTO public.book (title,date_added) VALUES('Старик и море', now());
INSERT INTO public.book (title,date_added) VALUES('Двадцать тысяч лье под водой', now());


INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Михаил Булгаков' limit 1), (select id from public.book where title = 'Мастер и Маргарита' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Михаил Булгаков' limit 1), (select id from public.book where title = 'Собачье сердце' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Илья Ильф' limit 1), (select id from public.book where title = 'Двенадцать стульев' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Евгений Петров' limit 1), (select id from public.book where title = 'Двенадцать стульев' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Николай Гоголь' limit 1), (select id from public.book where title = 'Мёртвые души' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Александр Дюма' limit 1), (select id from public.book where title = 'Граф Монте-Кристо' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Илья Ильф' limit 1), (select id from public.book where title = 'Золотой теленок' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Евгений Петров' limit 1), (select id from public.book where title = 'Золотой теленок' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Эрих Мария Ремарк' limit 1), (select id from public.book where title = 'Три товарища' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Виктор Гюго' limit 1), (select id from public.book where title = 'Отверженные' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Александр Пушкин' limit 1), (select id from public.book where title = 'Евгений Онегин' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Федор Достоевский' limit 1), (select id from public.book where title = 'Преступление и наказание' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Лев Толстой' limit 1), (select id from public.book where title = 'Война и мир' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Александр Пушкин' limit 1), (select id from public.book where title = 'Повести Белкина' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Николай Гоголь' limit 1), (select id from public.book where title = 'Ревизор' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Федор Достоевский' limit 1), (select id from public.book where title = 'Село Степанчиково и его обитатели' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Александр Дюма' limit 1), (select id from public.book where title = 'Три мушкетера' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Иван Тургенев' limit 1), (select id from public.book where title = 'Отцы и дети' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Антон Чехов' limit 1), (select id from public.book where title = 'Палата № 6' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Артур Конан Дойль' limit 1), (select id from public.book where title = 'Собака Баскервилей' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Федор Достоевский' limit 1), (select id from public.book where title = 'Братья Карамазовы' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Федор Достоевский' limit 1), (select id from public.book where title = 'Идиот' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Иван Тургенев' limit 1), (select id from public.book where title = 'Рудин' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Артур Конан Дойль' limit 1), (select id from public.book where title = 'Приключения Шерлока Холмса' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Александр Грибоедов' limit 1), (select id from public.book where title = 'Горе от ума' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Александр Пушкин' limit 1), (select id from public.book where title = 'Дубровский' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Антон Чехов' limit 1), (select id from public.book where title = 'Драма на охоте' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Александр Пушкин' limit 1), (select id from public.book where title = 'Капитанская дочка' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Федор Достоевский' limit 1), (select id from public.book where title = 'Униженные и оскорблённые' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Лев Толстой' limit 1), (select id from public.book where title = 'Воскресение' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Иван Тургенев' limit 1), (select id from public.book where title = 'Дворянское гнездо' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Антон Чехов' limit 1), (select id from public.book where title = 'Рассказы' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Эрих Мария Ремарк' limit 1), (select id from public.book where title = 'Триумфальная арка' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Федор Достоевский' limit 1), (select id from public.book where title = 'Подросток' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Эрнест Хемингуэй' limit 1), (select id from public.book where title = 'Старик и море' limit 1));
INSERT INTO public.author_book (author_id, book_id) VALUES((select id from public.author where name = 'Жюль Верн' limit 1), (select id from public.book where title = 'Двадцать тысяч лье под водой' limit 1));


